language: java

before_install:
  - wget $HAVEN
  - mvn install:install-file -DgroupId=com.oracle -DartifactId=ojdbc7 -Dpackaging=jar -Dversion=12.1.0 -Dfile=ojdbc7-12.1.0.jar -DgeneratePom=true

script:
  - mvn clean package
  - mvn sonar:sonar  -Dsonar.projectKey=1905-uta-java_TEAM_TIE  -Dsonar.organization=1905-uta-java  -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=$SONAR_TOKEN
